type Event {
    name: String!
    at: String
    description: String
    url: String
    trip: Trip! @relation
}
type Trip {
    name: String!
    events: [Event!] @relation
    user: User @relation
}
type User {
    name: String!
    email: String!
    trips: [Trip!] @relation
}
type Token @embedded {
    instance: ID
    secret: String
}
type Query {
    createUser(
        name: String!, 
        email: String!, 
        password: String!): User! @resolver(name: "create_user")
    getUser( id: ID! ): User!  @resolver(name: "get_user")
    loginUser(
        email: String!, 
        password: String!): Token! @resolver(name: "login_user")
}